### ISSUE TITLE
Add additional visualization 

### ISSUE THREAD

**Issue by allisonmeier** [allisonmeier/Project2#23]
*Choose one of the following additional visualizations: 

1) A visualization designed by your team showing the unstructured text data about the call and request.  This data is not available for all calls in the dataset, but if present, we want some representation of this unstructured text data, that gives the user an impression of the requests overall. As with the other charts, this should update when the user makes brushing selections. Sketch your approach, including encodings and interactions, and submit these sketches with your documentation. 
    
2) Add the ability for the user to switch from the map view showing all the calls, to a view showing a heat-map representation, which displays the number of calls in each cell in a grid you create over the city.  The heat map grid cells should size appropriately, as the user pans and zooms. Include tooltip interactions to show information about the calls in that grid cell. Brushing and linking interactions in other visualizations should update your heatmap 

3) Create a visualization which accomplishes an analysis task you are interested in exploring.  This visualization must be something other than a bar chart, line chart, pie chart or scatterplot. Clearly define the goals of this visualization- what do you want someone to learn from it? Describe any data transformation you performed. Describe how you arrived at the selected visual encoding and interaction design.  Include sketches. This visualization should be interactive and should tie-in with the interactions already created in your application (brushing and linking).

**Comment by man702020** [comment]
will attempt to generate a vertically stacked grouped bar chart for open, closed, and new issues for each month of 2022 data..

**Comment by man702020** [comment]
generate a stacked bar chart that shows open, closed and new system
